logo_title: 1van

style: white

favicon: /favicon.ico

tag_generator:
  per_page: 10
  order_by: -date


menu:
  作品: /project
  标签: /tags
  域名: /domain
  友联: /links
  关于: /about
  Github: https://github.com/1van-w

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: falese
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false